### ISSUE TITLE
2D Array X and Y

### ISSUE THREAD

**Issue by ThorgerJ** [TGlas/tscript#18]
Given the 2D Test Array:

`var arr = [[0,0,2,2,0],
[2,0,2,2,2],
[2,0,0,2,2],
[0,0,2,0,2]];`

The function `arr.size()` returns 4 where `arr[0].size()` returns 5

As far as I know 2D Arrays usually are represented in `arr[x][y]` but in this case it would be swapped to `arr[y][x]`.

Maybe im not thinking correctly here but I think this is confusing and counter intuitive.

**Comment by TGlas** [comment]
It is up to you what you call x and what you call y, and see also row-major vs. column-major matrices. However, it is clear that the sizes are correct: arr has 4 elements, while arr[0] has 5 elements.
I would argue that you got it wrong. For example, images are usually laid out so that arr[y][x] makes sense (inner arrays are rows).
