### ISSUE TITLE
Pressing [F3] in editor should jump to next occurence

### ISSUE THREAD

**Issue by manuel-fischer** [TGlas/tscript#25]
When pressing [F3] the text search of the browser is/(might be) activated instead of the search functionality of the editor itself, which can be activated by [Ctrl] + [F]. Pressing [F3] in editor should simply jump to next occurence of the text, that was previously typed into the searchbox.

**Comment by TGlas** [comment]
Hotkeys in browsers are generally a delicate issue: they tend to differ widely depending on the combination of browser and operating system. I agree that this would be a good thing, but I will have to see how to make it configurable.

**Comment by ThorgerJ** [comment]
The easiest way should be to let the user press the key in the config menu which then is recorded and used in the future. Thats atleast a common practice in videogames. There could be a default setting for the most common browser(s) though.

**Comment by TGlas** [comment]
It turns out that codemirror's search plugin has configurable hotkeys. I added F3 for "search next" and Shift+F3 for "search previous", which is now redundant on top of the build-in Ctrl+G and Shift+Ctrl+G hotkeys.
I may make the hotkey configurable at some point, but only if there is a real demand. Other hotkeys like Ctrl+F are also not configurable.
