### ISSUE TITLE
Function to get list of files/keys

### ISSUE THREAD

**Issue by manuel-fischer** [TGlas/tscript#32]
It might be useful to add a function, that collects the names of existing filenames/keys and puts them into an array. When I implemented LatticeCraft, I wondered how to implement the load/save dialogs, which should list all saved worlds. I was not able to get a list of all files without additional tricks. I ended up using a special "file" that stores all other "filenames" in an array, whenever a world was saved. There is currently no way to simply get a list of all file names/keys, that are created by the save function.

I would call the function `dir` like the DOS command. The same name is also used for a function in Python to get an array of the attribute names of an object. The name `list` could be confused with the datastructure.

Instead of

```
# what if the content of "file_list" is not an array of strings?
function save_data(file, data)
{
    # "register" file
    if not exists(file) then
    {
        var file_list = [];
        if exists("file_list") then
            file_list = load("file_list");
        save("file_list", concat([file], file_list));
    }
    save(file, data);
}

function list_files()
{
    if exists("file_list") then
    {
        for var file in load("file_list") do print(file);
    }
}
```

It should be possible to simply write

```
function save_data(file, data)
{
    save(file, data);
}

function list_files()
{
    for var file in dir() do print(file);
}

**Comment by Jartreg** [comment]
How about a more self-descriptive name like `getStorageKeys()` or just `storageKeys()`? Most users of TScript are beginners, and I doubt many of them have a DOS handbook lying around...

**Comment by TGlas** [comment]
"File" handling was very limited from the start. Most programming courses treat this topic in some depth, since it is obviously important for real projects. In the browser it is, well, problematic. One could either go ahead and integrate cloud services or live with a poor local storage solution. One could of course build a fully-fledged file system with nested directories on top of local storage, but it will be the victim of the next best cookie eater plugin. That's why I did not invest here. Nevertheless I think that a "dir" function is needed. For the name, I personally like `dir`, but I see that the name is not natural for the target audience. Python is often good at this. They use `os.listdir`, that's probably a bit more descriptive than just `dir`. However, this still needs the notions of a directory, and we don't really have that. How about `listfiles`, `getfilelist` or -- my favorite -- simply `filelist`?

**Comment by TheHllm** [comment]
Given that the arguments of `exists` , `load` and  `save` all use `key` as the 'filename' i would say `listKeys` makes the most sense.

**Comment by Jartreg** [comment]
@TGlas @manuel-fischer since this issue wasn't linked properly one of you should close it manually
