### ISSUE TITLE
Forward declarations, namespace objects

### ISSUE THREAD

**Issue by manuel-fischer** [TGlas/tscript#49]
In TScript it is sometimes difficult to call functions that are defined below the current function:
1. In C and C++ it is implemented with forward declarations, instead of the body a semicolon is written in the code to specify that the body is not yet possible to define.
2. In other scripting languages this problem is solved by resolving name lookup in functions whenever they are executed.
3. There might also be a middle approach that collects every identifier and tries to resolve identifiers to been looked up (identifiers that occurr anywhere except the introduced names after `var, namespace, class, function...` ) when the whole source was parsed. The lookup is done staticly once, but a function for example can be accessed from anywhere else in the code.

The following does not work (*):

```
function f() { g(); } # << error: error in expression; 'g' is not defined
function g() { f(); }

class C {}
namespace gameState {}
var score = 42;
```

0. current solution
```
var C;
var gameState;
var score;

class C_ {}
C = C_;
namespace gameState_ {}
gameState = gameState_; # << error: a name referring to a namespace is not allowed in this context
                        #    aka: namespaces are not objects
                        #    use class instead of namespace, impossible to nest classes
score = 42;
```

1. forward declarations
```
class C;
namespace gameState;
var score; # << note not a forward declaration

function g();
function f() { g(); }
function g() { f(); }

class C {}
namespace gameState {}
score = 42;
```
2. & 3. are exactly (*), possibly the easiest to understand for beginners

An alternative could be the ability to define namespaces and classes inside functions and namespaces. In addition to that, it might be useful to use a namespace as an object. As long as the namespace is accessed throught the original identifer the names are resolved staticly, otherwise the namespace behaves as an object, accessing a nested namespace through a namespace object would then result in another namespace object. Namespaces and namespace object share the scope of the contained elements. Changing a variable would change it in both.
When a class or namespace is declared in a function, a new version is created, that contains individual static values.

**Comment by TGlas** [comment]
I agree that the current behavior is not good. I strongly prefer the third approach. It requires two compiler passes through the code, but that's not a big deal, aside from the need to restructure the compiler.

For namespaces I don't see the problem. They don't need to be forward-declared, because it is possible to add entries to the same namespace multiple times. In other words, the following code works:

    namespace gameState { var x = 1; }
    print(gameState.x);
    namespace gameState { var y = 2; }
    print(gameState.x + gameState.y);

This means that

    namespace gameState { }

can be used as a forward declaration of the namespace itself. With a two-pass compiler, would that solve the namespace issue?

**Comment by manuel-fischer** [comment]
Alternatively the compiler could track, which names were used before their definition. If at the end any names are left, which do not refer to any global (scoped) variable, a compile time error occurrs. This probably leads to similar behavior to a two-pass compiler.

**Comment by Jartreg** [comment]
I like the idea of function declaration hoisting in JavaScript: it basically "pulls" the function/class declarations to the beginning of a scope. I'm not sure, but it sounds pretty similar to what you are describing??

More on this: [Hoisting — MDN](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting), [Function Declaration Hoisting — MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function#function_declaration_hoisting)

The (IMO) **cleanest** way to implement this would, as you said, be to separate the parsing and "compilation" (name resolution is the relevant part here) into two passes:

1. While parsing, the parser could maintain a list of function/class declarations for each scope...
2. ...which get used in the second pass to resolve names, independent from whether the name is referenced before or after the declaration. In @manuel-fischer's example (*), `g` would be found because it is already in the declaration list of the surrounding scopes.

Another solution would be to make name references an object that is in either state `unresolved` or `resolved`.

* When the parser encounters a reference, it tries to resolve it. If this fails, it adds it to a reference list of the enclosing scope. (I think this might be exactly what @manuel-fischer is describing with "the compiler could track, which names were used before their definition")
* When the parser encounters a declaration, it looks in the reference list for unresolved references for it and resolves these. (e.g. by setting a `resolvedTarget` property or sth. similar)

When the parser completes, all still unresolved references in the reference lists of each scope can never be resolved. This means that even in this variant, we would keep the ability to show name errors.

However, this might also have some downsides because we'd add another level of indirection (performance penalty?) and increase the complexity of the parser. (Are there elements that depend on the reference being known when they're parsed?)

Anyway, depending on how _desperately_ we want it to work, I wouldn't put off the two-pass solution entirely. The project isn't even fully typed yet, so I'd guess that some major necessary restructurings will happen anyways. I thought of this as a "nice to have" feature, how do you see this?

**Comment by TGlas** [comment]
Yes, JS-style function hoisting sounds good. However, I strongly dislike the semantics of the JS `let` statement, which essentially disallows the use of a variable name in the same scope before the declaration. So, doing this for functions, classes and namespaces is fine, but variables should work exactly the way they do right now.

As far as I can see, both solutions (one-pass and two-pass) should work equally well. The main difference from a user perspective is that for the two-pass solution, name resolution error messages will show up earlier than for the one-pass solution (say, if a name error precedes a syntax error). That's not a big deal though. I don't know if a two-pass approach potentially offers additional benefits, for example for type inference, which may help the compiler to generate more efficient code.

To answer your question: I don't think that this should have super high priority, but it would be nice to resolve it eventually. Or in shoft: nice to have.

**Comment by TGlas** [comment]
Hoisting of classes and functions is now implemented. Variables work as they used to, i.e., their names are not hoisted, with the exception of class scope: attributes are hoisted, hence the order of member declarations had become irrelevant.
