### ISSUE TITLE
[BUG] Canvas exports don't work in firefox

### ISSUE THREAD

**Issue by Jartreg** [TGlas/tscript#62]
In firefox, the canvas gets a size of 0x0:

<img width="728" alt="Canvas Export" src="https://user-images.githubusercontent.com/28811733/106260987-55ed7400-6221-11eb-8fa4-e2b82e7c7cd3.png">

_Originally found here: https://github.com/TGlas/tscript/pull/57#discussion_r566710549_

**Comment by TGlas** [comment]
The current code for setting the canvas size in `handleCanvas()` (in `src/tgui/standalone.ts`) reads:

    setTimeout( ()=>{
        cv.width = 250;
        cv.height = 250;
    }, 100);

At least on FF/Linux, removing this part and adding the following two lines solves the problem:

    ide.canvas.width = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
    ide.canvas.height = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight;

First of all, the current code sets width and height of the parent of the canvas, which is probably not intended. Then I don't know if we need the timeout delay at all. It is actually very dangerous, since the TScript code starts running immediately. Maybe I added the timeout at some point to improve robustness when later on the problem proved to be something completely different (just speculation, not sure about that any more, but well possible). Finally, did I introduce the value of 250 in the hope that a resize event would change it anyway? 250 does not make any sense here.

Could someone test this with different browsers / operating systems?

**Comment by TGlas** [comment]
I created the branch standalone-canvas-fixes, could you check if it helps on your side? I would be particularly interested in other browser/OS combinations.

**Comment by Jartreg** [comment]
On macOS, it works perfectly in Safari, Firefox and Chrome! It works even with a slight simplification of the code: [see comment](https://github.com/TGlas/tscript/commit/0e4454adf940f58b9bf6ed114be6029075ef32d0#r47014161)
